services:
  flight_manage:
    image: eightfingers123/ros1_zmq_tests:arm64
    
    container_name: flight_manager
    
    env_file:
      - 207.env
      
    ipc: host
    
    network_mode: host
  
    command: bash -c "source /ros1_ws/devel/setup.bash && stdbuf -o L roslaunch flight_manage flight_manage.launch"
    # command: stdbuf -o L roslaunch flight_manage flight_manage.launch
